name: parllel-jobs-hello-world
on:
  workflow_dispatch: 
jobs:
  shell-hello:
    runs-on: ubuntu-latest
    steps:
       - name: hello-shell
         run: echo "hello Shell"
  python-hello:
     runs-on: ubuntu-22.04
     steps:
       - name: python-hello
         run: print("Hello python")
         shell: python
         
         
  
