name: varibalestest
on:
 workflow_dispatch: 
jobs:
  consumer:
    runs-on: ubuntu-22.04
    outputs:
       test: ${{steps.generate-foo.outputs.pk}}
       test1: ${{steps.generate-foo.outputs.prem}}
    steps:
      - name: geneate and export 
        id: generate-foo
        run: | 
           foo=prem
           foi=pkprem
           echo "pk=${foo}" >> "$GITHUB_OUTPUT"
           echo "prem=${foi}" >> "$GITHUB_ENV"
           echo "yenne=${foi}" >> "$GITHUB_OUTPUT"
      - name: Inspacet values
        run: |
          echo "FOO=$prem"
          echo "foo=${{steps.generate-foo.outputs.pk}}"
  producer:
      runs-on: ubuntu-24.04
      needs: consumer
      steps:
        - name: get from producer
          run: |
            echo "ypk=${{needs.consumer.outputs.test}}"
            echo "pkp=${{needs.consumer.outputs.tes1}}"
    
           
